Update `utils.py` for the LIBRA task (#3520)
* Update `utils.py` for the LIBRA task

Instead of the outdated pymorphy2 library, it is proposed to use pymorphy3.

* Update vllm_causallms.py

Fix the bug `TypeError: Unexpected keyword argument 'max_gen_toks'` in the vllm_causalllms.py module.