Update setup.py
Running `main.py` yields the following:

```
ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`
```

This commit should fix this.